### ISSUE TITLE
How to setup duration

### ISSUE THREAD

**Issue by NizarBsb** [snipsco/react-inview-monitor#22]
Hello,

Thank you very much for this great library for React, works very well. However, looking at the properties list I don't see how I can set up the animation duration.

**Comment by pocketjoso** [comment]
Hi,
This library does not handle animations directly, that's why there are no such properties. The easiest way to deal with inv view animations is to let this library add your animation classes as an element comes into view. In this case, it will be up to your css to declare the `animation-duration`.
